# Generated by Django 3.2.15 on 2023-09-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("patients_count", models.BigIntegerField()),
                ("specimens_count", models.BigIntegerField()),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
    ]
