# Generated by Django 3.2.15 on 2023-09-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_runstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runstats",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="runstats",
            name="patients_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="runstats",
            name="specimens_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
