# Generated by Django 3.2.15 on 2023-09-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20230922_1628"),
    ]

    operations = [
        migrations.AddField(
            model_name="runconfiguration",
            name="celery_frequency_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="runconfiguration",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
