# Generated by Django 3.2.15 on 2023-09-29 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20230928_1109"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RunStats",
        ),
    ]
