# Generated by Django 3.2.18 on 2023-09-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_delete_runstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="runconfiguration",
            name="bridgehead_host",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="runconfiguration",
            name="bridgehead_pass",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="runconfiguration",
            name="bridgehead_user",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="runconfiguration",
            name="mapping_config",
            field=models.TextField(default="{}", max_length=10000),
        ),
    ]
