# Generated by Django 3.2.18 on 2023-09-29 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20230929_1155"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RunConfiguration",
            new_name="EtlConfiguration",
        ),
    ]
