# Generated by Django 3.2.18 on 2023-10-06 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_runconfiguration_etlconfiguration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etlconfiguration",
            old_name="celery_frequency_days",
            new_name="celery_frequency_hours",
        ),
    ]
